### ISSUE TITLE
Anbox 3 unable to connect with the session manager

### ISSUE THREAD

**Issue by WPFilmmaker** [anbox/anbox#662]
**anbox system-info:**
`stuff@stuff-VirtualBox:~$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2018-03-26 16:51:22] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2018-03-26 16:51:27] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2018-03-26 16:51:32] [launch.cpp:134@operator()] Anbox session manager service isn't running, trying to start it.
[ 2018-03-26 16:51:37] [launch.cpp:206@operator()] Couldn't get a connection with the session manager`

**Printout of anbox system-info:**
`stuff@stuff-VirtualBox:~$ anbox system-info
libEGL warning: DRI2: failed to authenticate
version: 3
snap-revision: 72
os:
  name: Ubuntu
  version: 16.04.4 LTS (Xenial Xerus)
  snap-based: true
kernel:
  version: Linux version 4.4.0-116-generic (buildd@lgw01-amd64-021) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 17.2.8
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_polygon_offset_clamp
      - GL_KHR_no_error`

**Please describe your problem:**
Anbox 3 crashes.

**What were you expecting?:**
Anbox 3 would work.

**Additional info:**
My OS is Lubuntu 16.04.3. #471 is identical to this, but @mrpew says he fixed it (on Linux Mint 18), by upgrading to version 3, and the ticket was closed in November 2017. However on my system it has not been fixed and I am using v. 3 so I decided to open this ticket.

**Comment by AdoPi** [comment]
Did you try to start session-manager with this command?
```
anbox session-manager --gles-driver=translator 
```

**Comment by WPFilmmaker** [comment]
@AdoPi I tried now and I get:

`[ 2018-03-27 15:00:53] [runtime.cpp:41@exception_safe_run] write: Broken pipe
[ 2018-03-27 15:00:53] [runtime.cpp:41@exception_safe_run] write: Broken pipe`

Then terminal gets stuck

**Comment by spencerreeves** [comment]
@WPFilmmaker Any updates on this issue?

**Comment by WPFilmmaker** [comment]
@spencerreeves Actually yes, I tried again with the same command and I get:
`libEGL warning: DRI2: failed to authenticate
[ 2018-08-06 15:08:31] [Renderer.cpp:193@initialize] Failed: Missing egl_image related extension(s)
Stack trace (most recent call last) in thread 3282:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fca64ccc41c, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7fca6675f6b9, in 
#4    Object "/snap/anbox/92/usr/bin/anbox", at 0x572220, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/92/usr/bin/anbox", at 0x4a40dc, in RenderThread::main()
#2    Object "/snap/anbox/92/usr/bin/anbox", at 0x56e9da, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/92/usr/bin/anbox", at 0x516c5e, in 
#0    Object "/snap/anbox/92/usr/bin/anbox", at 0x554eb5, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)`

**Comment by spencerreeves** [comment]
@WPFilmmaker Unfortunately I am not actually getting the same error as you. I was however, getting the issue with the broken pipe. I fixed the issue by increasing the processors and cpus on my virtual machine to 2 and 4096 respectively. Are you running this on a virtual machine?

**Comment by WPFilmmaker** [comment]
@spencerreeves Yes i am on a vm! Apologiez for not specifying it! I will do the changes you suggested and try again.

**Comment by WPFilmmaker** [comment]
@spencerreeves 
I tried the changes and still get the same error:

lubuntu@pc:~$ anbox session-manager --gles-driver=translator
libEGL warning: DRI2: failed to authenticate
[ 2018-08-15 12:29:08] [Renderer.cpp:193@initialize] Failed: Missing egl_image related extension(s)
Stack trace (most recent call last) in thread 2976 :
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fab43daa41c, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7fab4583d6b9, in
#4    Object "/snap/anbox/92/usr/bin/anbox", at 0x572220, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/92/usr/bin/anbox", at 0x4a40dc, in RenderThread::main()
#2    Object "/snap/anbox/92/usr/bin/anbox", at 0x56e9da, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/92/usr/bin/anbox", at 0x516c5e, in
#0    Object "/snap/anbox/92/usr/bin/anbox", at 0x554eb5, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)

Which is the same error as my previous message only the thread is different (now it is 2976 before it was 3282)
