### ISSUE TITLE
Anbox Ignores Mouse Input

### ISSUE THREAD

**Issue by thebombzen** [anbox/anbox#780]
**anbox system-info:**
https://0x0.st/s9dS.log

**Please describe your problem:**
Anbox ignores all mouse input in any android application and also in the application manager. It's not a repainting issue, because resizing the window or moving it off and back onto the screen causes a repaint, but the mouse input still does nothing.

**What were you expecting?:**
I expected Anbox to respond to the mouse in the calculator, settings, or application manager.

**Additional info:**
This is not a duplicate of #582 since that bug was not actually fixed by the PR that closed it, and would not be reopened. Instead, I submitted a new issue since my request to reopen it was ignored and the issue remains.

I'm running Anbox on Arch Linux, version anbox-git 1:r895.9a95b53-1 from the AUR.

**Comment by morphis** [comment]
@thebombzen I am sorry for that. #582 was a mixture of reports about Intel and Nvidia and the PR fixed problems only with Intel GPUs. However your problem looks different. Can you follow the instructions you were given on bug creation and provide all details?

**Comment by thebombzen** [comment]
As you can see from my `anbox system-info` log, I'm running anbox outside of a snap-based environment.

**Comment by morphis** [comment]
@thebombzen That is fine but we still need more info from your side in order to find out what is wrong. Please include the following things in your bug report (this is what `anbox.collect-bug-info` does):

 * `/var/lib/anbox/data/system.log`
 * `/var/lib/anbox/containers/lxc-monitor.log`
 * `/var/lib/anbox/logs/*`
 * `journalctl --no-pager -u snap.anbox.container-manager`
 * `dmesg`

**Comment by thebombzen** [comment]
@morphis Here are the logs:
`/var/lib/anbox/data/system.log`: https://0x0.st/sfz4.log
`/var/lib/anbox/containers/lxc-monitor.log`: No such file or directory
`/var/lib/anbox/logs/container.log`: https://0x0.st/sfzJ.log
`/var/lib/anbox/logs/console.log`: https://0x0.st/sfzy.log
`journalctl --no-pager -u anbox-container-manager.service`: https://0x0.st/sfzw.log
`dmesg`: https://0x0.st/sfzx.log

**Comment by thebombzen** [comment]
Should the needs-info tag be removed now that I've provided info?

**Comment by plygrnd** [comment]
```
$ anbox system-info
version: 4
snap-revision: 92
os:
  name: Ubuntu
  version: 18.04 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-29-generic (buildd@lgw01-amd64-057) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_display_reference
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_nvrm_fence_sync
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_reset
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 3.2 NVIDIA 390.77
    extensions:
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clear_texture
      - GL_EXT_clip_control
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_color_buffer_half_float
      - GL_EXT_conservative_depth
      - GL_EXT_copy_image
      - GL_EXT_debug_label
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_float_blend
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_indirect
      - GL_EXT_multisample_compatibility
      - GL_EXT_multisampled_render_to_texture
      - GL_EXT_multisampled_render_to_texture2
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_post_depth_coverage
      - GL_EXT_primitive_bounding_box
      - GL_EXT_raster_multisample
      - GL_EXT_render_snorm
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_non_constant_global_initializers
      - GL_EXT_shader_texture_lod
      - GL_EXT_shadow_samplers
      - GL_EXT_sparse_texture
      - GL_EXT_sparse_texture2
      - GL_EXT_sRGB
      - GL_EXT_sRGB_write_control
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_bptc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_filter_minmax
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_mirror_clamp_to_edge
      - GL_EXT_texture_norm16
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_storage
      - GL_EXT_texture_view
      - GL_EXT_draw_transform_feedback
      - GL_EXT_unpack_subimage
      - GL_EXT_window_rectangles
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_KHR_parallel_shader_compile
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_EXT_semaphore
      - GL_EXT_semaphore_fd
      - GL_NV_bgr
      - GL_NV_bindless_texture
      - GL_NV_blend_equation_advanced
      - GL_NV_blend_equation_advanced_coherent
      - GL_NVX_blend_equation_advanced_multi_draw_buffers
      - GL_NV_blend_minmax_factor
      - GL_NV_clip_space_w_scaling
      - GL_NV_conditional_render
      - GL_NV_conservative_raster
      - GL_NV_conservative_raster_pre_snap_triangles
      - GL_NV_copy_buffer
      - GL_NV_copy_image
      - GL_NV_draw_buffers
      - GL_NV_draw_instanced
      - GL_NV_draw_texture
      - GL_NV_draw_vulkan_image
      - GL_NV_EGL_stream_consumer_external
      - GL_NV_explicit_attrib_location
      - GL_NV_fbo_color_attachments
      - GL_NV_fill_rectangle
      - GL_NV_fragment_coverage_to_color
      - GL_NV_fragment_shader_interlock
      - GL_NV_framebuffer_blit
      - GL_NV_framebuffer_mixed_samples
      - GL_NV_framebuffer_multisample
      - GL_NV_generate_mipmap_sRGB
      - GL_NV_geometry_shader_passthrough
      - GL_NV_instanced_arrays
      - GL_NV_internalformat_sample_query
      - GL_NV_gpu_shader5
      - GL_NV_image_formats
      - GL_NV_occlusion_query_samples
      - GL_NV_non_square_matrices
      - GL_NV_pack_subimage
      - GL_NV_packed_float
      - GL_NV_packed_float_linear
      - GL_NV_path_rendering
      - GL_NV_path_rendering_shared_edge
      - GL_NV_pixel_buffer_object
      - GL_NV_polygon_mode
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_NV_sample_locations
      - GL_NV_sample_mask_override_coverage
      - GL_NV_shader_atomic_fp16_vector
      - GL_NV_shader_noperspective_interpolation
      - GL_NV_shadow_samplers_array
      - GL_NV_shadow_samplers_cube
      - GL_NV_sRGB_formats
      - GL_NV_stereo_view_rendering
      - GL_NV_texture_array
      - GL_NV_texture_barrier
      - GL_NV_texture_border_clamp
      - GL_NV_texture_compression_latc
      - GL_NV_texture_compression_s3tc
      - GL_NV_texture_compression_s3tc_update
      - GL_NV_timer_query
      - GL_NV_viewport_array
      - GL_NV_viewport_array2
      - GL_NV_viewport_swizzle
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_OES_depth24
      - GL_OES_depth32
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_texture_border_clamp
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_buffer
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_gpu_shader5
      - GL_OES_shader_io_blocks
      - GL_OES_texture_view
      - GL_OES_primitive_bounding_box
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_image_external_essl3
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_surfaceless_context
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_npot
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
      - GL_ANDROID_extension_pack_es31a
```
[anbox-system-diagnostics-2018-07-22.zip](https://github.com/anbox/anbox/files/2220096/anbox-system-diagnostics-2018-07-22.zip)

**Comment by fhteagle** [comment]
On Ubuntu 18.04 / Gnome,  it appears that android activity windows lose focus even while clicking in them. I can reliably restore focus by moving the activity window (but not by resizing). With no focus, "highlighting" of the menu item under the mouse, etc stops. After a window move, the highlighting reliably follows the mouse again.

This loss of focus is not seen in enlightenment 21 on the same Ubuntu install.

anbox system-info:
version: 4
snap-revision: 133
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) m7-6Y75 CPU @ 1.20GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-29-generic (buildd@lgw01-amd64-057) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.0.5
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array

**Comment by thebombzen** [comment]
Are you sure that's the same bug as the bug being reported?

**Comment by fhteagle** [comment]
No, not positive they are the same symptoms of the same bug. Just trying to add info to a "need info" tagged bug. If you have something specific that you would like me to test to add more specific info, let me know and I will be happy to oblige.

**Comment by mihakrut** [comment]
version: 0.0~git20180709-1-Debian
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  features: 
    - aes
    - ssse3
    - sse4_1
    - sse4_2
    - avx
    - ssse3
    - avx2
os:
  name: Kali GNU/Linux
  version: 2018.2
  snap-based: false
kernel:
  version: Linux version 4.16.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-24)) #1 SMP Debian 4.16.16-2kali2 (2018-07-04)
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions:
      - n/a
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.1.4
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_image_external_essl3
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array

**Comment by morphis** [comment]
#587 tests a theory by disabling the anbox-touch input device we hook next to the anbox-pointer into the container as according to the logs posted here it feels like the Android system gets confused by multiple devices at times. Once merged I would encourage everyone who experiences this bug to test again if it fixes the issue or not. If you do that and the issue remains, please again attach the output of `anbox.collect-bug-info`.

**Comment by morphis** [comment]
@thebombzen ^^

**Comment by sstahl4006** [comment]
Morphis, how do I disable the anbox-touch input device as you mentioned above?

**Comment by morphis** [comment]
Just refresh the snap from the edge channel via `snap refresh --edge --devmode anbox`Am 11.08.2018 23:43 schrieb sstahl4006 <notifications@github.com>:Morphis, how do I disable the anbox-touch input device as you mentioned above?

**Comment by sstahl4006** [comment]
Tried it. Still not working.

**Comment by jlsnow301** [comment]
Same issue, running i5 6600k / logitech mouse and keyboard / onboard GPU. Tried multiple installs over fresh Ubuntu 18.04.1 and Mint 19.  
[console.log](https://github.com/anbox/anbox/files/2289066/console.log)
[container.log](https://github.com/anbox/anbox/files/2289067/container.log)
[container-manager.log](https://github.com/anbox/anbox/files/2289068/container-manager.log)
[system.log](https://github.com/anbox/anbox/files/2289070/system.log)
[system-info.log](https://github.com/anbox/anbox/files/2289071/system-info.log)

**Comment by jlsnow301** [comment]
Issue still present in new edge build, 08/17/18

**Comment by morphis** [comment]
Can everyone who commented, list which desktop environment they are using?

**Comment by bionicdude** [comment]
I have the same issue.
Standard Ubuntu 18.04 (gnome, right?).
Might be worth mentioning that i use one of those logitech universal dongles for my trackpad keyboard.
only because i see another user mention logitech.
I also have that solaar battery/status indicator stuff installed.

**Comment by jlsnow301** [comment]
I tried this on clean installs of Mint Cinnamon 64bit and Ubuntu Gnome 64bit. Both had the same issue.

**Comment by thebombzen** [comment]
I'm in Arch Linux using MATE.

**Comment by sstahl4006** [comment]
Linux Mint 19 Cinnamon desktop
Intel Corei5-8400 with integrated graphics

**Comment by sstahl4006** [comment]
Quick question. Since so many of us seem to be having this issue, is there a keyboard command or some other way that we can open apps in the application manager? If not, could that be added in to the next build?

**Comment by mihakrut** [comment]
snap refresh --devmode --edge anbox
fixed

**Comment by sstahl4006** [comment]
Refreshed. Still not working.

**Comment by digidoug** [comment]
I can confirm, Ubuntu 18.04 moving to the --edge did not eliminate the problem. Here's my `anbox system-info`:
version: 4
snap-revision: 143
cpu:
  arch:  x86
  brand: AMD FX(tm)-8120 Eight-Core Processor           
  features: 
    - aes
    - sse4_1
    - sse4_2                                                                                                                         
    - avx                                                                                                                            
os:                                                                                                                                  
  name: Ubuntu                                                                                                                       
  version: 18.04.1 LTS (Bionic Beaver)                                                                                               
  snap-based: true                                                                                                                   
kernel:                                                                                                                              
  version: Linux version 4.15.0-33-generic (buildd@lcy01-amd64-024) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018                                                                                                              
  binder: true                                                                                                                       
  ashmem: true                                                                                                                       
graphics:                                                                                                                            
  egl:                                                                                                                               
    vendor: Mesa Project                                                                                                             
    version: 1.5 (DRI2)                                                                                                              
    extensions:                                                                                                                      
      - EGL_CHROMIUM_sync_control                                                                                                    
      - EGL_EXT_buffer_age                                                                                                           
      - EGL_EXT_create_context_robustness                                                                                            
      - EGL_EXT_image_dma_buf_import                                                                                                 
      - EGL_KHR_cl_event2                                                                                                            
      - EGL_KHR_config_attribs                                                                                                       
      - EGL_KHR_create_context                                                                                                       
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES 3.1 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array

**Comment by digidoug** [comment]
I might also add that cursor keys from the keyboard don't work either.  Wondering if it is the wireless keyboard?  I'm using a Logitech K350 Keyboard/mouse

**Comment by olympus123** [comment]
I have the same issue, Ubuntu 18.04.1 LTS
Mouse and keyboard doesn't work.

https://paste.ubuntu.com/p/987gfYYhPv/

I had Anbox installed some months ago on 17.10 and mouse and keyborad worked, with the same hardware I have now.

**Comment by TiS** [comment]
Same thing, using edge or beta channel. Right now anbox is completely unusable.

Info:

version: 4
snap-revision: 146
cpu:
  arch:  x86
  brand:         Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-33-generic (buildd@lcy01-amd64-024) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.0 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robustness
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float

**Comment by TiS** [comment]
Additional info:

Running session manager gives me "address already in use" error. I don't know, if this might be relevant, though:

anbox session-manager
[ 2018-09-04 08:55:47] [daemon.cpp:61@Run] bind: Address already in use

**Comment by rumytaulu** [comment]
I have the same issue, mouse (and keyboard) working on app manager and I can launch application by clicking it, but as soon the application start, I can not click on any button, pointer and keyboard is working though.

OS : Linux Mint 18.3 Sylvia
DE : Cinnamon
Graphic Card Intel and Nvidia (tried both with no luck)
Attached is my log
[anbox-system-diagnostics-2018-12-01.zip](https://github.com/anbox/anbox/files/2635644/anbox-system-diagnostics-2018-12-01.zip)

**Comment by douglasg14b** [comment]
Having a similar issue, but can't click on anything in the application manager. Installed via snap, beta channel.

Anbox BETA
OS : Ubuntu 18.10
DE : KDE Plasma
Graphic Card: AMD rx580
2 wireless mice

[anbox systme info.txt](https://github.com/anbox/anbox/files/2716094/anbox.systme.info.txt)

**Comment by frenzisys** [comment]
> I am experiencing the same issue and what I discovered so far is it might be caused by sth in the android system. When I started the session-manager in single window mode, I saw the "Power off" UI widget overlaying the app manager, which means, any input is actually sent to the "Power off" UI, that may explain why in multi-window mode, mouse input does not work.
> ![anbox_single_win](https://user-images.githubusercontent.com/46290809/50570290-ad6f3c00-0d4a-11e9-8835-f24f2373cbef.png)

same for me

**Comment by dbdashij** [comment]
> I am experiencing the same issue and what I discovered so far is it might be caused by sth in the android system. When I started the session-manager in single window mode, I saw the "Power off" UI widget overlaying the app manager, which means, any input is actually sent to the "Power off" UI, that may explain why in multi-window mode, mouse input does not work.
> ![anbox_single_win](https://user-images.githubusercontent.com/46290809/50570290-ad6f3c00-0d4a-11e9-8835-f24f2373cbef.png)

The shutdown request/intent is sent by BatteryService::shutdownIfNoPowerLocked when battery level is 0 and the *device* is not wire-powered. So an easy workaround is comment the code snippet in shutdownIfNoPowerLocked which sends the ACTION_REQUEST_SHUTDOWN intent. I don't know why this happens on AMD TR 1920x + Geforce GTX 1070 w/ ubuntu 16.04.5 LTS but not i7-4790k + Quadro P2000 w/ ubuntu 16.04.5 LTS.

**Comment by morphis** [comment]
Can you propose a PR for this?Am 03.01.2019 04:16 schrieb dbdashij <notifications@github.com>:
I am experiencing the same issue and what I discovered so far is it might be caused by sth in the android system. When I started the session-manager in single window mode, I saw the "Power off" UI widget overlaying the app manager, which means, any input is actually sent to the "Power off" UI, that may explain why in multi-window mode, mouse input does not work.


The shutdown request/intent is sent by BatteryService::shutdownIfNoPowerLocked when battery level is 0 and the device is not wire-powered. So an easy workaround is comment the code snippet in shutdownIfNoPowerLocked which sends the ACTION_REQUEST_SHUTDOWN intent. I don't know why this happens on AMD TR 1920x + Geforce GTX 1070 w/ ubuntu 16.04.5 LTS but not i7-4790k + Quadro P2000 w/ ubuntu 16.04.5 LTS.

**Comment by dbdashij** [comment]
> Can you propose a PR for this?Am 03.01.2019 04:16 schrieb dbdashij <notifications@github.com>: I am experiencing the same issue and what I discovered so far is it might be caused by sth in the android system. When I started the session-manager in single window mode, I saw the "Power off" UI widget overlaying the app manager, which means, any input is actually sent to the "Power off" UI, that may explain why in multi-window mode, mouse input does not work. The shutdown request/intent is sent by BatteryService::shutdownIfNoPowerLocked when battery level is 0 and the device is not wire-powered. So an easy workaround is comment the code snippet in shutdownIfNoPowerLocked which sends the ACTION_REQUEST_SHUTDOWN intent. I don't know why this happens on AMD TR 1920x + Geforce GTX 1070 w/ ubuntu 16.04.5 LTS but not i7-4790k + Quadro P2000 w/ ubuntu 16.04.5 LTS. —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

Found the root cause. android healthd tries to read battery level/capacity from /sys/class/power_supply/*/capacity if it exists otherwise the level/capacity is set to 0. On my i7-4790k rig, the logitech unifying receiver reports my mouse battery level in the capacity file (non-zero); on my tr 1920x rig, it's a different logitech mouse and it does not present the capacity file.

to fix this, add ro.boot.fake_battery=1 to build.prop, healthd then will use hard-coded values for both battery level and temperature. Hope this can fix others' mouse input issue.

**Comment by morphis** [comment]
@dbdashij I've pushed a PR (see above) to set the property early on startup.

I am going to see if this causing any regression but if not I will merge and would like to hear from others experiencing this bug if it got fixed.

**Comment by morphis** [comment]
The fix linked above is now available in the edge channel. Please try it out and comment if it fixes the issue for you.

**Comment by bionicdude** [comment]
fixed it for me. thanks everyone.

**Comment by digidoug** [comment]
Yup, that's the magic! Thanks!

**Comment by morphis** [comment]
Thanks all!

**Comment by bentolor** [comment]
Thank you very much everbody! This fix also works for me, too and finally made anbox usable for me at all.

**Comment by MunGhanGha** [comment]
Sorry guys, but I do not know how I can do this ... Please could someone tell me what are the terminal commands I have to do?

> > Can you propose a PR for this?Am 03.01.2019 04:16 schrieb dbdashij [notifications@github.com](mailto:notifications@github.com): I am experiencing the same issue and what I discovered so far is it might be caused by sth in the android system. When I started the session-manager in single window mode, I saw the "Power off" UI widget overlaying the app manager, which means, any input is actually sent to the "Power off" UI, that may explain why in multi-window mode, mouse input does not work. The shutdown request/intent is sent by BatteryService::shutdownIfNoPowerLocked when battery level is 0 and the device is not wire-powered. So an easy workaround is comment the code snippet in shutdownIfNoPowerLocked which sends the ACTION_REQUEST_SHUTDOWN intent. I don't know why this happens on AMD TR 1920x + Geforce GTX 1070 w/ ubuntu 16.04.5 LTS but not i7-4790k + Quadro P2000 w/ ubuntu 16.04.5 LTS. —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
> 
> Found the root cause. android healthd tries to read battery level/capacity from /sys/class/power_supply/*/capacity if it exists otherwise the level/capacity is set to 0. On my i7-4790k rig, the logitech unifying receiver reports my mouse battery level in the capacity file (non-zero); on my tr 1920x rig, it's a different logitech mouse and it does not present the capacity file.
> 
> to fix this, add ro.boot.fake_battery=1 to build.prop, healthd then will use hard-coded values for both battery level and temperature. Hope this can fix others' mouse input issue.

**Comment by thebombzen** [comment]
There's no need to do this because this bug has been fixed in the latest git master.

**Comment by bentolor** [comment]
@MunGhanGha To update: `sudo snap refresh --devmode --edge anbox` 
To install:  `sudo snap install --devmode --edge anbox` if not installed

**Comment by MunGhanGha** [comment]
> @MunGhanGha To update: `sudo snap refresh --devmode --edge anbox`
> To install: `sudo snap install --devmode --edge anbox` if not installed

Thank you guys! But issue do not solved...  -> git version 2.17.1

$ anbox system-info
version: 4
snap-revision: 169
cpu:
  arch:  x86
  brand:        Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-43-generic (buildd@lgw01-amd64-001) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.0 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robustness
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float

**Comment by MunGhanGha** [comment]
I can install the game 'Ragnarok M: Eternal Love' and I was stuck at the "confirm button" initial screen...

**Comment by MunGhanGha** [comment]
Thank you for your attention guys! I solved the problem by installing windows and run perfectly with the MUMU emulator! CYA!

**Comment by daviaws** [comment]
Same issue here:
![50v94](https://user-images.githubusercontent.com/12686471/51704688-cf35a900-2000-11e9-9898-a9823d7023c0.png)

I saw there were other issues with more basic apps, like calculator and schedule, and it's already fixed.
But it seems that some apps are unable to click yet...

**Comment by morphis** [comment]
@daviaws That is most likely because the app only accepts touch input events but Anbox only sends mouse input events. It's not easy for us to detect that and do the right thing.

**Comment by blintwave** [comment]
@morphis I can say I have the same problem @daviaws has as well. For some reason this only happens to me when I run some games but the more simple apps like a file manager the mouse input works. I have to say I just been using Anbox for a little bit so I have not tested a lot of apps.

**Comment by daviaws** [comment]
@morphis if you cannot detect it automatically, could we at least have an option to configure manually the default option for each application?

**Comment by flyer0402** [comment]
> I have the same issue, Ubuntu 18.04.1 LTS with the latest edge snap of Anbox.
> Mouse and keyboard don't work.
> 
> https://paste.ubuntu.com/p/987gfYYhPv/
> 
> I had Anbox installed some months ago on 17.10 and mouse and keyboard worked, with the same hardware I have now.

How did you solve the problem?

**Comment by Afsalmc** [comment]
**For Non Snap users :_)**
Apparently the issue is still present in latest version . You can start session manager with `--no-touch-emulation` to avoid the issue .
After starting container-manager service run `anbox session-manager --no-touch-emulation&` and wait some time to fully load the system . Then launch Anbox from menu icon shortcut .
